# Contains k8s objects that don't belong in the namespace
# to which the JupyterHub is deployed.
{{ if .Values.createNamespace -}}
# Create the namespace itself
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.name }}
{{- end }}
{{ if eq .Values.singleuser.storage.type "dynamic" -}}
---
# Dynamic provisioner for the single-user server pods
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: single-user-storage-{{ default .Release.Namespace .Values.name }}
provisioner: {{ .Values.singleuser.storage.storageClass.provisioner }}
parameters:
{{ toYaml .Values.singleuser.storage.storageClass.parameters | indent 2}}
{{- end }}
{{ if eq .Values.hub.db.type "sqlite-pvc" -}}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: hub-storage-{{ default .Release.Namespace .Values.name }}
provisioner: {{ .Values.hub.db.storageClass.provisioner }}
parameters:
{{ toYaml .Values.hub.db.storageClass.parameters | indent 2}}
{{- end }}
