# Default values for jupyterhub-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Name of this installation. Will be used to create namespace
# and storageclass. Must be a valid DNS label
# HACK: need to get rid of this, purely use --namespace only
name: null

# Ideally, we should not be creating namespaces in our templates.
# Helm can create the when you use --namespace, and we should
# just use those. However, leaving this here for a while to
# make sure we do not break current installations.
createNamespace: false

# Deprecated, use proxy.secretToken instead
token:
  proxy: null

hub:
  baseUrl: "/"
  cookieSecret: null
  publicURL: null
  db:
    type: sqlite-pvc
    storageClass:
      provisioner: kubernetes.io/gce-pd
      parameters:
        type: pd-ssd
    url: null
  labels: null
  extraConfig: null
  image:
    name: yuvipanda/jupyterhub-k8s-hub
    tag: v0.3.1
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi

builder:
  enabled: false
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
  image:
    name: yuvipanda/jupyterhub-k8s-builder
    tag: v0.3.1
  registry:
    prefix: null
    host: gcr.io
    username: _json_key
    password: null


proxy:
  secretToken: 'generate with openssl rand -hex 64'
  image:
    name: yuvipanda/jupyterhub-k8s-proxy
    tag: v0.3.1
  resources:
    requests:
      cpu: 0.2
      memory: 512Mi
  labels: null

# Set this explicitly if you want to use a static allocated
# IP as the public LoadBalancer IP. Requires support by
# your Cloud Provider. GKE supports this
publicIP: null

# Google OAuth secrets
auth:
  type: dummy
  dummy:
    password: null

singleuser:
  extraLabels: {}
  extraEnv: {}
  lifecycleHooks: null
  storage:
    type: dynamic
    storageClass:
      provisioner: kubernetes.io/gce-pd
      parameters:
        type: pd-ssd

    capacity: 10Gi
    homeMountPath: /home/jovyan
    # type: hostPath
    # homeHostPathTemplate: /data/project/paws/userhomes/{userid}
  image:
    # name: yuvipanda/jupyterhub-k8s-singleuser-sample
    name: jupyter/scipy-notebook
    # tag: v0.3.1
    tag: latest
  cpu:
    limit: null
    guarantee: null
  memory:
    limit: null
    guarantee: 1G
  cmd: jupyterhub-singleuser

prePuller:
  enabled: true
  image:
    name: yuvipanda/image-allnodes-puller
    tag: v0.8

cull:
  enabled: true
  timeout: 3600
  every: 600

statsd:
  enabled: false
  port: 8125
  host: statsd
  prefix: jupyterhub

admin:
  access: true
  users: null
